Add wrpcontext package, Add new decoder
xmidt-org/wrp-go pull request #116
Opened 2023-03-30 14:55 UTC by renaz6

- closes #114  and #115

2023-04-06 22:12 UTC, johnabass requested changes

2023-04-06 22:12 UTC, johnabass commented on wrpcontext/wrpcontext.go
> +type contextKey string
A better way to declare a context key is simply to do:

```
type contextKey struct{}
```

You would then use it as: 

```
msg := context.Value(contextKey{})
```

No further code is necessary.

2023-04-06 22:12 UTC, johnabass commented on wrpcontext/wrpcontext.go
> +func GetAs(ctx context.Context, msg any) bool {
Unmarshal/Marshal isn't necessary.  There's quite a lot of overhead with marshaling when all you want is a type conversion.

You can handle all the possible cases via a combination of `reflect` and some simple type checking.  Using a generic function not only makes a client's use easier, but also simplifies the implementation:

```
func GetAs[T any](ctx context.Context) (dest T, ok bool) {
    src := ctx.Value(contextKey{})
    if src == nil {
        return
    } 

    // trivial case: src and dest are the exact same type
    if dest, ok = src.(T); ok {
        return
    }

    // second case: src is a pointer to the same type as the value of dest
    var srcptr *T
    if srcptr, ok = src.(*T); ok {
        if srcptr == nil {
            ok = false
        } else {
            dest = *srcptr
        }

        return
    }

    // third case: src is a value, but dest is a pointer to that same value
    // we need to drop into the reflect package for this
    srcValue := reflect.ValueOf(src)
    destType := reflect.TypeOf((*T)(nil)).Elem()
    ok = srcValue.Kind() != reflect.Ptr && destType.Kind() == reflect.Ptr && srcValue.Type().ConvertibleTo(destType.Elem())

    if ok {
        // use reflect to create a pointer to T's element type, which will allocate memory
        // then we copy src to that memory
        destValue := reflect.New(destType.Elem())
        destValue.Elem().Set(srcValue)
        dest = destValue.Interface().(T)
    }

    return
```

2023-04-07 15:23 UTC, denopink requested changes
I agree with john's requested changes

2023-04-12 00:46 UTC, johnabass commented on wrphttp/decoders_test.go
> +func testDecodeRequestSuccess(t *testing.T) {
Not a blocker, but we should start moving consistently to github.com/stretchr/testify/suite for test suites.  That makes these kinds of subtests much clearer and easier to implement and maintain.

2023-04-12 00:46 UTC, johnabass approved these changes

2023-04-12 14:59 UTC, renaz6 commented on wrphttp/decoders_test.go
> +func testDecodeRequestSuccess(t *testing.T) {
Added this issue to cover this work: https://github.com/xmidt-org/wrp-go/issues/121

2023-04-12 15:11 UTC, denopink approved these changes

2023-04-12 15:57 UTC, merged